### ISSUE TITLE
failed to create decoder for rtsp://127.0.0.1:8554/test_video 

### ISSUE THREAD

**Issue by SokPhanith** [JoeTester1965/CudaCamz#1]
Hello 
When I run : python3 CudaCam.py config.txt
I got error : 
2021-07-05:16:22:20,720 INFO     [CudaCam.py:530] CudaCam started
2021-07-05:16:22:20,720 INFO     [CudaCam.py:536] Remapped rtsp://172.20.120.10:8080/h264_ulaw.sdp to rtsp://127.0.0.1:8554/thiscamera as using_rtsp_simple_proxy set
2021-07-05:16:22:20,721 INFO     [CudaCam.py:536] Remapped file:///home/phanith/CudaCam/test.mp4 to rtsp://127.0.0.1:8554/test_video as using_rtsp_simple_proxy set
[gstreamer] initialized gstreamer, version 1.14.5.0
[gstreamer] gstDecoder -- creating decoder for 127.0.0.1
[gstreamer] gstDecoder -- Could not open resource for reading and writing.
[gstreamer] gstDecoder -- pipeline string:
[gstreamer] rtspsrc location=rtsp://127.0.0.1:8554/thiscamera latency=2000 ! queue ! rtph264depay ! h264parse ! omxh264dec ! video/x-raw ! appsink name=mysink
[video]  created gstDecoder from rtsp://127.0.0.1:8554/thiscamera
------------------------------------------------
gstDecoder video options:
------------------------------------------------
  -- URI: rtsp://127.0.0.1:8554/thiscamera
     - protocol:  rtsp
     - location:  127.0.0.1
     - port:      8554
  -- deviceType: ip
  -- ioType:     input
  -- codec:      h264
  -- width:      0
  -- height:     0
  -- frameRate:  0.000000
  -- bitRate:    0
  -- numBuffers: 4
  -- zeroCopy:   true
  -- flipMethod: none
  -- loop:       0
  -- rtspLatency 2000
------------------------------------------------
[gstreamer] gstDecoder -- creating decoder for 127.0.0.1
[gstreamer] gstDecoder -- Could not open resource for reading and writing.
[gstreamer] gstDecoder -- try manually setting the codec with the --input-codec option
[gstreamer] gstDecoder -- failed to create decoder for rtsp://127.0.0.1:8554/test_video
Traceback (most recent call last):
  File "CudaCam.py", line 545, in <module>
    rtsp_streams[friendly_name] = jetson.utils.videoSource(uri, ['me', input_codec_string])
Exception: jetson.utils -- failed to create videoSource device

**Comment by JoeTester1965** [comment]
Hi.

Not sure if issue is with 'test_video' or 'thiscamera' or both 

As documented in example config file, you can only use a local video file for testing if no rtsp  proxy is used (i.e. set using_rtsp_simple_proxy  = 0 in config file).

Regards thiscamera, remember that as in README, you must rerun 'python3 ./configure.py ./config.txt' if any cameras are added or removed from config file. Please test your camera URIs with something like VLC media player first and see how that goes.

Regards

Joe
