### ISSUE TITLE
No cameras are operational, will shut down

### ISSUE THREAD

**Issue by mlittle408** [JoeTester1965/CudaCamz#2]
I am seeing this in the logfile:

2021-10-03:10:11:27,136 INFO     [CudaCam.py:530] CudaCam started
2021-10-03:10:11:27,137 INFO     [CudaCam.py:536] Remapped rtsp://username:password@192.168.1.231:554/live to rtsp://127.0.0.1:8554/test as using_rtsp_simple_proxy set
2021-10-03:10:11:32,445 INFO     [CudaCam.py:547] Starting inference engine, can take a while
2021-10-03:10:11:38,412 INFO     [CudaCam.py:549] Inference engine is up
2021-10-03:10:11:38,413 INFO     [CudaCam.py:588] Starting cameras and getting test images for /tmp/mutelist_reminder, can take a while
2021-10-03:10:11:48,537 ERROR    [CudaCam.py:492] Camera test is not up, removing.
2021-10-03:10:11:48,538 CRITICAL [CudaCam.py:504] No cameras are operational, wIll shut down.

The RTSP stream (rtsp://username:password@192.168.1.231:554/live) works fine using VLC. When I set use_rtsp_simple_proxy=0, everything works great. Objects are detected, etc. When I set use_rtsp_simple_proxy=1, it fails.

Did I miss something?

**Comment by JoeTester1965** [comment]
Hi, with use_rtsp_simple_proxy=1, can you open rtsp://127.0.0.1:8554/test with VLC to test if the RTSP proxy is running?  (note: if not running VLC on your jetson nano you will need to replace 127.0.0.1 above with the appropriate IP address of your jetson nano in VLC).  

To test the RTSP proxy, go to the dir running cudacam then:

killall  rtsp-simple-server
cd rtsp-simple-server
./rtsp-simple-server

and see what comes out on terminal.

**Comment by mlittle408** [comment]
I did what you recommended and here's what I got: (192.168.1.156 is the machine I'm running VLC on). Also, I see the messages about a firewall and I am not running one. 

2021/10/03 12:50:45 [I] [0/0/0] rtsp-simple-server v0.14.2
2021/10/03 12:50:45 [I] [0/0/0] [UDP/RTP listener] opened on :8000
2021/10/03 12:50:45 [I] [0/0/0] [UDP/RTCP listener] opened on :8001
2021/10/03 12:50:45 [I] [0/0/0] [TCP/RTSP listener] opened on :8554
2021/10/03 12:50:45 [I] [0/0/0] [path test] [rtsp source] started
2021/10/03 12:50:45 [I] [0/0/0] [path test] [rtsp source] connecting
2021/10/03 12:50:46 [I] [0/0/0] [path test] [rtsp source] ready
2021/10/03 12:50:48 [I] [1/0/0] [client 127.0.0.1:46652] connected (plain)
2021/10/03 12:50:50 [I] [1/0/1] [client 127.0.0.1:46652] is reading from path 'test', 2 tracks with udp
2021/10/03 12:50:55 [I] [0/0/0] [client 127.0.0.1:46652] disconnected
2021/10/03 12:50:55 [I] [1/0/0] [client 127.0.0.1:46654] connected (plain)
2021/10/03 12:50:56 [I] [1/0/0] [path test] [rtsp source] ERR: no UDP packets received recently (maybe there's a firewall/NAT in between)
2021/10/03 12:50:56 [I] [0/0/0] [client 127.0.0.1:46654] disconnected
2021/10/03 12:51:01 [I] [0/0/0] [path test] [rtsp source] connecting
2021/10/03 12:51:02 [I] [0/0/0] [path test] [rtsp source] ready
2021/10/03 12:51:09 [I] [1/0/0] [client 192.168.1.156:58771] connected (plain)
2021/10/03 12:51:10 [I] [1/0/1] [client 192.168.1.156:58771] is reading from path 'test', 2 tracks with udp
2021/10/03 12:51:12 [I] [1/0/1] [path test] [rtsp source] ERR: no UDP packets received recently (maybe there's a firewall/NAT in between)
2021/10/03 12:51:12 [I] [0/0/0] [client 192.168.1.156:58771] disconnected
2021/10/03 12:51:17 [I] [0/0/0] [path test] [rtsp source] connecting
2021/10/03 12:51:18 [I] [0/0/0] [path test] [rtsp source] ready
2021/10/03 12:51:20 [I] [1/0/0] [client 192.168.1.156:63029] connected (plain)
2021/10/03 12:51:20 [I] [1/0/1] [client 192.168.1.156:63029] is reading from path 'test', 2 tracks with tcp
2021/10/03 12:51:28 [I] [1/0/1] [path test] [rtsp source] ERR: no UDP packets received recently (maybe there's a firewall/NAT in between)
2021/10/03 12:51:28 [I] [0/0/0] [client 192.168.1.156:63029] disconnected
2021/10/03 12:51:33 [I] [0/0/0] [path test] [rtsp source] connecting
2021/10/03 12:51:34 [I] [0/0/0] [path test] [rtsp source] ready
2021/10/03 12:51:44 [I] [0/0/0] [path test] [rtsp source] ERR: no UDP packets received recently (maybe there's a firewall/NAT in between)
2021/10/03 12:51:49 [I] [0/0/0] [path test] [rtsp source] connecting
2021/10/03 12:51:50 [I] [0/0/0] [path test] [rtsp source] ready
2021/10/03 12:52:00 [I] [0/0/0] [path test] [rtsp source] ERR: no UDP packets received recently (maybe there's a firewall/NAT in between)
2021/10/03 12:52:05 [I] [0/0/0] [path test] [rtsp source] connecting
2021/10/03 12:52:06 [I] [0/0/0] [path test] [rtsp source] ready
2021/10/03 12:52:11 [I] [1/0/0] [client 192.168.1.156:56494] connected (plain)
2021/10/03 12:52:11 [I] [1/0/1] [client 192.168.1.156:56494] is reading from path 'test', 2 tracks with udp
2021/10/03 12:52:16 [I] [1/0/1] [path test] [rtsp source] ERR: no UDP packets received recently (maybe there's a firewall/NAT in between)
2021/10/03 12:52:16 [I] [0/0/0] [client 192.168.1.156:56494] disconnected
2021/10/03 12:52:21 [I] [0/0/0] [path test] [rtsp source] connecting
2021/10/03 12:52:22 [I] [1/0/0] [client 192.168.1.156:52774] connected (plain)
2021/10/03 12:52:22 [I] [1/0/0] [client 192.168.1.156:52774] ERR: no one is publishing to path 'test'
2021/10/03 12:52:22 [I] [0/0/0] [client 192.168.1.156:52774] disconnected
2021/10/03 12:52:22 [I] [0/0/0] [path test] [rtsp source] ready

**Comment by JoeTester1965** [comment]
Mmm.  The RTSP proxy seems to connect but is not getting any data back. 

1. Maybe your camera can only have one client connected at a time - try disconnecting anything else connected to it.
2. Maybe your camera has a firewall or IP/MAC address based security options on it?
3. Maybe your camera will work if configured it explicitly to use TCP not UDP as UDP seems to be failing (there may be an option somewhere in the camera config to set RTSP as using TCP not UDP).

Best.

**Comment by mlittle408** [comment]
I appreciate the quick responses. It's the Wyze Cam 3 with the new RTSP firmware. There's no option for changing from UDP to TCP. I also tested it with multiple connections and it works fine and the camera doesn't have any security settings other than a username/password. 

It's odd though, CudaCam is working just fine with the stream. If I don't use rtsp_simple_server I get object detection, etc. It works just fine. I can see the images and video in the /tmp/images and /tmp/videos directories. 

Does rtsp_simple_server also connect to the camera or does CudaCam rebroadcast through rtsp_simple_server?

Thanks again for your help.

**Comment by JoeTester1965** [comment]
Hi.
The RTSP proxy just makes things more network and camera CPU efficient if you have multiple things wanting to use it, is an optional thing. See diagram here:
https://github.com/JoeTester1965/CudaCamz/blob/main/scope.jpg

**Comment by mlittle408** [comment]
Oh, so it's not actually showing the real-time object detection. Well, then I don't even need it. Awesome! Thanks, enjoy the rest of your Sunday. That's what I get for not paying attention to that diagram!!!
